spring:
  datasource:
    url: jdbc:postgresql://dpg-csijfkt2ng1s739k8nq0-a:5432/sxt
    username:sxt_user
    password:XeoxAOlVSsU5nOZwLQHMsMGOFZq4rEG0
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  hikari:
    connection-timeout: 30000
    maximum-pool-size: 10
    minimum-idle: 5
  hibernate:
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  transaction:
    default-timeout: 30
