spring:
  datasource:
    url: jdbc:postgresql://dpg-csijfkt2ng1s739k8nq0-a.oregon-postgres.render.com:5432/sxt
    username: sxt_user
    password: XeoxAOlVSsU5nOZwLQHMsMGOFZq4rEG0
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
