spring:
  datasource:
    url: jdbc:postgresql://<RENDER_DB_HOST>:<RENDER_DB_PORT>/<RENDER_DB_NAME>
    username: <RENDER_DB_USERNAME>
    password: <RENDER_DB_PASSWORD>
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
