spring:
  datasource:
    url: jdbc:postgresql://dpg-csijfkt2ng1s739k8nq0-a.oregon-postgres.render.com/sxt
    username: sxt_user
    password: XeoxAOlVSsU5nOZwLQHMsMGOFZq4rEG0
  jpa:
    hibernate:
      ddl-auto: update
server: 
  port: 10010
