spring:
  application:
    name: ds

  datasource:
    url:  jdbc:postgresql://dpg-csijfkt2ng1s739k8nq0-a.oregon-postgres.render.com:5432/sxt
    username: sxt_user
    password: XeoxAOlVSsU5nOZwLQHMsMGOFZq4rEG0
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate.format_sql: true
        #hibernate.boot.allow_jdbc_metadata_access: false
    # Uncomment below if needed
    # properties:
    #   hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    #   hibernate.show_sql: true
    #   hibernate.hbm2ddl.auto: update
    #   entitymanager.packagesToScan: <packages-to-scan>

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

SPRING_PROFILES_ACTIVE: dev
